### ISSUE TITLE
Fix Twitter Link

### ISSUE THREAD

**Issue by mabdullahsoyturk** [agucomputersociety/agucomputersociety.github.io#5]
Current twitter link is wrong. It needs to be fixed.

**Comment by Mehrabkb** [comment]
hi the twitter link where is it?

**Comment by halilbilgin** [comment]
It can be configured from the _config.yml file. Then, you can follow README.md to run the website locally and test your changes before sending pull request.

**Comment by mabdullahsoyturk** [comment]
Commit 6dcffa0c1f1191956a5504953b049efd39b11dde fixes this.
